### ISSUE TITLE
Shifting ownership

### ISSUE THREAD

**Issue by Arkagaen** [Aerakor/NSAA#13]
I know this is something for you...
I gave you something: maximusalmeida.github.io
It doesn't do anything, but it will be mp.aerakor.com.
NSAA is a branch of Aerakor, so, naturally, it should be in the GitHub organization.
So, please go to settings, click on transfer ownership, and give it to Aerakor.
Keep on hacking,
Louis
P.S. This is like an email

**Comment by MaximusAlmeida** [comment]
Okay, sorry bout that. I've done it.

**Comment by MaximusAlmeida** [comment]
I'm not sure if I've done it...

**Comment by Arkagaen** [comment]
You haven't

**Comment by MaximusAlmeida** [comment]
It should be pending

**Comment by MaximusAlmeida** [comment]
That's what the setting thing says

**Comment by Arkagaen** [comment]
There we go

**Comment by MaximusAlmeida** [comment]
Is it good?

**Comment by Arkagaen** [comment]
Yes
Look at your URL

**Comment by Arkagaen** [comment]
You still need to accept maximusalmeida.github.io

**Comment by Arkagaen** [comment]
It will be the repo for mp.aerakor.com

**Comment by MaximusAlmeida** [comment]
How?

**Comment by Arkagaen** [comment]
check your email and accept transfer

**Comment by Arkagaen** [comment]
Once you have done that, I will show you

**Comment by MaximusAlmeida** [comment]
Done

**Comment by Arkagaen** [comment]
Messaging here is tedious
Plz go to aelon
